[package]
name = "gvko-minigrep"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Small lib made just for practicing purposes of the Rust lang"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
